### PR TITLE
Fix run_exports

### LINKED ISSUE #12: No run_exports information contained in libode package
Despite https://github.com/conda-forge/libode-feedstock/pull/5, it seems that `info/run_exports.json` is not contained in the libode packages, see for example https://anaconda.org/conda-forge/libode/0.16.2/download/linux-64/libode-0.16.2-he226ad3_6.tar.bz2 .

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fix #12 

Checked locally and it now works as expected.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Same approach taken as in https://github.com/conda-forge/thrift-cpp-feedstock/blob/master/recipe/meta.yaml

**Comment by Tobias-Fischer** [comment]
~~Latest commit also fixes #9.~~ - couldn't get that to work and undid changes re this

**Comment by Tobias-Fischer** [comment]
This is ready for review @traversaro @repagh

Seems like #9 is trickier to fix than what I thought; so limiting to fix #12 for now

**Comment by Tobias-Fischer** [comment]
Ping @traversaro

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks, this was something I was not able to crack in the past. @conda-forge/libode any further comment?

**Comment by Tobias-Fischer** [comment]
Thanks for checking the PR, @traversaro. @repagh - any chance of merging this?

**Comment by traversaro** [comment]
> 
> 
> Thanks for checking the PR, @traversaro. @repagh - any chance of merging this?

I wanted to wait for @repagh input if any arrives, and then I can merge myself.

**Pull request merged**
