### PR TITLE
fix up pcconfig file

### PR DESCRIPTION
**Pull request by wolfv**
@traversaro maybe you can review this :)

### CODE REVIEW

**Comment by wolfv** [comment]
Hmm, the linking fails with 

```
LINK : warning LNK4044: unrecognized option '/LD:/bld/libode_1635751983796/_h_env/Library/lib'; ignored
LINK : warning LNK4044: unrecognized option '/lode_double'; ignored
```

**Comment by traversaro** [comment]
Differently from most other user of pkg-config I saw on Windows (including CMake's function [`pkg_check_modules`](https://cmake.org/cmake/help/v3.22/module/FindPkgConfig.html#command:pkg_check_modules) ) the ode's Python setup.py expect the `.pc` file to contain exactly the flags expected by `cl.exe`, i.e. the MSVC compiler (see https://bitbucket.org/odedevs/ode/src/0b5080331d9551e5e6689ebe6eb899809b5ba392/bindings/python/setup.py#lines-13). 

Probably it is also necessary to add the `--msvc-syntax` pkg-config flag to all invocations of `pkg-config` in the `setup.py`, see https://gitlab.freedesktop.org/pkg-config/pkg-config/-/blob/d97db4fae4c1cd099b506970b285dc2afd818ea2/README.win32#L24 for more info.

**Comment by traversaro** [comment]
Indeed the patch https://github.com/conda-forge/libode-feedstock/pull/15/commits/82726b7d535aaa9d07366f8a3d4be64d7fb46b56 (applied only on Windows) seems to be working fine.

**Comment by traversaro** [comment]
@repagh what do you think? It seems good to me.

**Comment by wolfv** [comment]
Looks good to me, too.

**Pull request merged**
