### PR TITLE
Use pin_subpackage in run_exports and fix installation of CMake config in Windows

### PR DESCRIPTION
**Pull request by traversaro**
Modification:
* Use pin_subpackage in run_exports: to ensure that the version is taken in consideration in run_exports
* The CMake config files were not include in the `libode` package on Windows, this PR includes them and check that they are correctly installed.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
fyi @wolfv

**Comment by wolfv** [comment]
Yep, that should be much better. Without the pin_subpackage it would only add `libode` to the run requirements, but without a lower or upper bound afaik.

**Comment by traversaro** [comment]
> 
> 
> Yep, that should be much better. Without the pin_subpackage it would only add `libode` to the run requirements, but without a lower or upper bound afaik.

Yes, the problem that I had in https://github.com/conda-forge/libignition-physics-feedstock/pull/12 was exactly that, where libode 0.16.0 got installed but dart actually needed libode 0.16.2 .

**Comment by traversaro** [comment]
To avoid having only a single maintainer for the recipe, if you like @repagh I can also add myself as a maintainer.

**Comment by repagh** [comment]
Thank you, looks good. And yes, if @traversaro want to join as maintainer, fine. 

Glad to see more people have a use for libode

**Comment by traversaro** [comment]
Thanks @repagh ! I create a PR to add myself as mantainer to reduce the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) in https://github.com/conda-forge/libode-feedstock/pull/6 . Obviously I will wait for your opinion on all future PRs in any case!

**Pull request merged**
